name: Daily bash generate.sh

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: whois
          version: 1.0

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run generate.sh
        run: bash -ex -o pipefail generate.sh > ips.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ips.txt
          git commit -m "Auto-update ips.txt [daily job]"
          git push
